# Generated by Django 3.1.5 on 2021-01-31 08:09

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='website',
            name='words',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
