# Generated by Django 3.1.5 on 2021-01-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20210131_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='words',
            field=models.CharField(max_length=10000),
        ),
    ]
