# Generated by Django 3.1.5 on 2021-01-31 09:06

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20210131_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='words',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
